### ISSUE TITLE
Update app dependencies + version strategy

### ISSUE THREAD

**Issue by borsi** [SenseNet/sn-react-redux-todo-app#4]
Check current status of our todo example apps and determine the course of action.

## Tasks
- [x] Add greenkeeper to all of these apps
- [x] Have a short term strategy for fixing these repos
- [x] Devise a long term version strategy to be future-proof

**Comment by herflis** [comment]
- [react todo app](https://github.com/SenseNet/sn-react-redux-todo-app) is updated and published
- [vuejs app](https://github.com/SenseNet/sn-vue-redux-todo-app) base should be recreated with a vuejs+webpack cli. I've created a issue for that in the repo of the vuejs todoapp
